// <auto-generated />
using System;
using F1API.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace F1API.Migrations
{
    [DbContext(typeof(F1Context))]
    [Migration("20231106184200_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("F1API.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageURL")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("F1API.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Driver1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Driver2Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageURL")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Driver1Id");

                    b.HasIndex("Driver2Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("F1API.Models.Team", b =>
                {
                    b.HasOne("F1API.Models.Driver", "Driver1")
                        .WithMany()
                        .HasForeignKey("Driver1Id");

                    b.HasOne("F1API.Models.Driver", "Driver2")
                        .WithMany()
                        .HasForeignKey("Driver2Id");

                    b.Navigation("Driver1");

                    b.Navigation("Driver2");
                });
#pragma warning restore 612, 618
        }
    }
}
